# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_books', to='likes.User'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploader',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likes.User'),
            preserve_default=False,
        ),
    ]
